model:
  model_path : "gpt2"
  model_type : "SentimentILQLModel"
  device : "cuda"

train:
  n_ctx : 512
  epochs : 10
  batch_size : 8
  grad_clip : 1.0

  lr_ramp_steps : 100
  lr_decay_steps : 3366
  weight_decay : 1.0e-6
  learning_rate_init : 1.0e-4
  learning_rate_target : 3.0e-6

  log_interval : 25
  checkpoint_interval : 100
  eval_interval : 100

  pipeline : "SentimentPipeline"
  orchestrator : "OfflineSentimentOrchestrator"

  accelerate : False
