model:
  model_path : "gpt2"
  model_type : "SentimentILQLModel"
  device : "cuda"
  tokenizer_path: "gpt2"
  num_layers_unfrozen: -1

train:
  n_ctx : 512
  epochs : 200
  batch_size : 100
  grad_clip : 1.0

  lr_ramp_steps : 100
  lr_decay_steps : 3366
  weight_decay : 1.0e-6
  learning_rate_init : 1.0e-3
  learning_rate_target : 1.0e-3

  log_interval : 25
  checkpoint_interval : 100
  eval_interval : 100

  gen_size: 10

  pipeline : "SentimentPipeline"
  orchestrator : "OfflineSentimentOrchestrator"

  accelerate : true

method:
  name: "ilqlconfig"
  tau: 0.5
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 1
  steps_for_target_q_sync: 40
  eval_beta: 1
  two_qs: true
