wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.3.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1657404007
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.8.5
      5: 0.12.21
      6: 4.3.2
      8:
      - 5
batch_size:
  desc: null
  value: 64
cliprange:
  desc: null
  value: 0.2
cliprange_value:
  desc: null
  value: 0.2
forward_batch_size:
  desc: null
  value: 16
gamma:
  desc: null
  value: 1
horizon:
  desc: null
  value: 10000
init_kl_coef:
  desc: null
  value: 0.2
lam:
  desc: null
  value: 0.95
lr:
  desc: null
  value: 1.41e-05
model_name:
  desc: null
  value: EleutherAI/gpt-neo-125M
ppo_epochs:
  desc: null
  value: 4
steps:
  desc: null
  value: 20000
target:
  desc: null
  value: 6
txt_in_max_len:
  desc: null
  value: 8
txt_in_min_len:
  desc: null
  value: 2
txt_out_max_len:
  desc: null
  value: 16
txt_out_min_len:
  desc: null
  value: 4
vf_coef:
  desc: null
  value: 0.1
